server:
  port: 8080

spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://orderservice:8081
          predicates:
            - Path=/api/orders/**

        - id: inventory-service
          uri: http://inventoryservice:8082
          predicates:
            - Path=/api/inventory/**

        - id: kitchen-service
          uri: http://kitchenservice:8083
          predicates:
            - Path=/api/kitchen/**

      default-filters:
        - AddResponseHeader=X-Gateway, SmartCakeShop

management:
  endpoints:
    web:
      exposure:
        include: health,info


