server:
  port: 8083

spring:
  application:
    name: kitchenservice
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kitchendb}
    username: ${DB_USER:kitchen_user}
    password: ${DB_PASSWORD:kitchen_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8081}


